WasabiTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/wasabi_3255.root
  TreeName: OutputTree
  BranchName: WasabiData
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

EuricaTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/eurica_3255.root
  TreeName: OutputTree
  BranchName: ClusterData
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

BigRIPSTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/bigrips_3255.root
  TreeName: OutputTree
  BranchName: BigRIPSData
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

WasabiMergedTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/eurica_wasabi_3255.root
  TreeName: OutputTree
  BranchName: EuricaWasabi
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

ImplantTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/implant_3255.root
  TreeName: OutputTree
  BranchName: Implant
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

BetaTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/implant_3255.root
  TreeName: OutputTree
  BranchName: Implant
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

EuricaWasabiMerger:
  OutputFileName: /home/ryokoyam/data/eurica/eurica_wasabi_3255.root
  TreeName: OutputTree
  BranchName: EuricaWasabi
  ClassName: eurica::EuricaWasabiData
  TimeWindowLow: 1000
  TimeWindowUp: 1000
  TimeStampScale: 1
  ScanWindow: 1E+9

ImplantMerger:
  OutputFileName: /home/ryokoyam/data/eurica/implant_3255.root
  TreeName: OutputTree
  BranchName: Implant
  ClassName: eurica::ImplantData
  TimeWindowLow: 1000
  TimeWindowUp: 1000
  TimeStampScale: 1
  ScanWindow: 1E+9
  FillEmpty: True

BetaTreeMerger:
  OutputFileName: /home/ryokoyam/data/eurica/beta_3255.root
  TreeName: OutputTree
  BranchName: Beta
  ClassName: eurica::BetaData
  TimeWindowLow: 1000000000
  TimeWindowUp: 1000000000
  TimeStampScale: 1
  ScanWindow: 1E+9
  FillEmpty: False
  CorrelationRadius: 1.0
  