WasabiTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/WASABI3142.root
  TreeName: WASABI
  BranchName: data
#  OtherBranches:
#  FirstEntry: 0
#  LastEntry: 10000

EuricaTSScanner:
  InputFileName: /home/ryokoyam/data/eurica/go4_3142.root
  TreeName: tree
  BranchName: EventInfo
  OtherBranches:
    - "UnpackEvent"
    - "GeCluster"
    - "GeAddback"
    - "BetaPlasticUp"
    - "BetaPlasticDown"
    - "BigRIPSRaw"
#  FirstEntry: 0
#  LastEntry: 10000

S2PlusTSScanner:
  InputFileName: /home/sh13/rootfiles/test.root
  TreeName: SH13S2PlusTree
  PixieBranchName: SH13S2PlusData
  PrintFrequency: 100000
  #OtherBranches:
  #  - "clover_vec_"
  #  #- "event_info_"
  #  #- "file_name"
  #  #- "pixie_event_num"
#  FirstEntry: 0
#  LastEntry: 1000000

Merger:
  OutputFileName: rootfiles/merged_0083.root
  TreeName: merged
  BranchName: merged
  ClassName: OutputTreeData<ULong64_t, S2PlusData>
  TimeWindowLow: -100000
  TimeWindowUp: 100000
  TimeStampScale: 1
  ScanWindow: 1E+9